version: "3"

networks:
  minio_network:
    external: false

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - ${MINIO_ROOT}:/data
    ports:
      - 9000:9000
      - 9001:9001
    restart: unless-stopped
    networks:
      - minio_network
    command: minio server /data --console-address ":9001"    
