services:
  nextcloud-tailscale:
    image: tailscale/tailscale:latest
    container_name: nextcloud-tailscale
    restart: unless-stopped
    init: true
    environment:
      - TS_AUTHKEY=${TAILSCALE_OAUTH_KEY}?ephemeral=false # ?ephemeral=true for testing/development
      - TS_HOSTNAME=${TAILSCALE_HOSTNAME}
      - TS_EXTRA_ARGS=--advertise-tags=tag:container # --reset for testing/development
      - TS_SERVE_CONFIG=/config/tailscale-nextcloud.json
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - /dev/net/tun:/dev/net/tun
      - nextcloud-tailscale-data:/var/lib/tailscale
      - ./tailscale-config:/config
    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks:
      - nextcloud-aio
  
  nextcloud-aio:
    image: nextcloud/all-in-one:latest
    container_name: nextcloud-aio-mastercontainer   # DO NOT CHANGE
    restart: unless-stopped
    depends_on:
      - nextcloud-tailscale
    networks:
      - nextcloud-aio
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      APACHE_PORT: 11000
      APACHE_IP_BINDING: 0.0.0.0
      SKIP_DOMAIN_VALIDATION: true
      NEXTCLOUD_DATADIR: ${NEXTCLOUD_DATADIR}

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer
  nextcloud-tailscale-data:
    name: nextcloud-tailscale-data

networks:
  nextcloud-aio:
    name: nextcloud-aio
    driver: bridge
    enable_ipv6: false
    driver_opts:
      com.docker.network.driver.mtu: "9001" # Jumbo Frame
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1" # Harden aio (only if ports are exposed)
