version: '3.8'
services:
  mqtt:
    container_name: mosquitto
    image: eclipse-mosquitto:2.0.15
    restart: unless-stopped
    volumes:
      - "/home/wmutschl/docker/mosquitto-data:/mosquitto"
#    ports:
#      - "1883:1883"
#      - "9001:9001"
    network_mode: "host"
    command: "mosquitto -c /mosquitto-no-auth.conf"

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:1.30.4
    restart: unless-stopped
    volumes:
      - /home/wmutschl/docker/zigbee2mqtt-data:/app/data
      - /run/udev:/run/udev:ro
    #ports:
    #  - 8080:8080
    network_mode: "host"
    environment:
      - TZ=Europe/Berlin
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0

  homebridge:
    container_name: homebridge
    image: oznu/homebridge:2023-01-08
    restart: unless-stopped
    network_mode: host
    volumes:
      - /home/wmutschl/docker/homebridge:/homebridge
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
    environment:
      - TZ=Europe/Berlin
      - ENABLE_AVAHI=1