version: "3"

networks:
  nextcloud_network:

services:
  swag:
    image: lscr.io/linuxserver/swag:1.32.0-ls170
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      - URL=${URL}
      - VALIDATION=http
      - EMAIL=${EMAIL}
      - ONLY_SUBDOMAINS=false
      - EXTRA_DOMAINS=www.${URL},${NEXTCLOUD_DOMAIN}
      - CERTPROVIDER=letsencrypt
      - DOCKER_MODS=linuxserver/mods:swag-dashboard
    volumes:
      - ${SWAG_ROOT}:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
    networks:
      - nextcloud_network

  nextcloud:
    image: lscr.io/linuxserver/nextcloud:25.0.2-ls216
    container_name: nextcloud
    environment:
      - PUID=1000
      - GUID=1000
      - TZ=${TIMEZONE}
    volumes:
      - ${NEXTCLOUD_ROOT}/config:/config
      - ${NEXTCLOUD_ROOT}/data:/data
    depends_on:
      - mariadb
      - redis
    restart: unless-stopped
    networks:
      - nextcloud_network

  mariadb:
    image: lscr.io/linuxserver/mariadb:10.6.10-r0-ls79
    container_name: mariadb
    environment:
      - PUID=1000
      - GUID=1000
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${TIMEZONE}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ${NEXTCLOUD_ROOT}/mariadb:/config
    restart: unless-stopped
    networks:
      - nextcloud_network

  redis:
    image: redis:7.0.7
    container_name: nextcloud-redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: unless-stopped
    networks:
      - nextcloud_network
