version: "3"

networks:
  nextcloud_network:
    name: nextcloud_network
  gitea_network:
    name: gitea_network

services:
  swag:
    image: lscr.io/linuxserver/swag:3.2.0-ls363
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      - URL=${SWAG_URL}
      - SUBDOMAINS=${SWAG_SUBDOMAINS}
      - EXTRA_DOMAINS=${SWAG_EXTRA_DOMAINS}
      - VALIDATION=${SWAG_VALIDATION}
      - DNSPLUGIN=${SWAG_DNSPLUGIN}
      - EMAIL=${SWAG_EMAIL}
      - CERTPROVIDER=${SWAG_CERTPROVIDER}
    volumes:
      - ${SWAG_ROOT}:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
    networks:
      - nextcloud_network
      - gitea_network

  nextcloud:
    image: lscr.io/linuxserver/nextcloud:30.0.5-ls366
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      - DOCKER_MODS=linuxserver/mods:nextcloud-notify-push
    volumes:
      - ${NEXTCLOUD_ROOT}/config:/config
      - ${NEXTCLOUD_ROOT}/data:/data
    depends_on:
      - nextcloud-mariadb
      - nextcloud-redis
    restart: unless-stopped
    networks:
      - nextcloud_network

  nextcloud-mariadb:
    image: lscr.io/linuxserver/mariadb:11.4.4-r1-ls173
    container_name: nextcloud-mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      - MYSQL_DATABASE=${NEXTCLOUD_MARIADB_DATABASE}
      - MYSQL_USER=${NEXTCLOUD_MARIADB_USER}
      - MYSQL_PASSWORD=${NEXTCLOUD_MARIADB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${NEXTCLOUD_MARIADB_PASSWORD_ROOT}
    volumes:
      - ${NEXTCLOUD_ROOT}/mariadb:/config
    restart: unless-stopped
    networks:
      - nextcloud_network

  nextcloud-redis:
    image: redis:7.4.2-bookworm
    container_name: nextcloud-redis
    command: redis-server --requirepass ${NEXTCLOUD_REDIS_PASSWORD}
    restart: unless-stopped
    networks:
      - nextcloud_network

  gitea:
    image: gitea/gitea:1.23.3
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - DOMAIN=${GITEA_DOMAIN}
      - RUN_MODE=prod
      - LFS_START_SERVER=true
      - GITEA__repository__DEFAULT_BRANCH=main
      - GITEA__oauth2__JWT_SECRET=${GITEA_JWT_SECRET}
      - GITEA__security__SECRET_KEY=${GITEA_SECRET_KEY}
      - GITEA__security__INTERNAL_TOKEN=${GITEA_INTERNAL_TOKEN}
      - GITEA__security__INSTALL_LOCK=true
      - GITEA__server__DISABLE_SSH=true
      - GITEA__server__LFS_JWT_SECRET=${GITEA_LFS_JWT_SECRET}
      - GITEA__server__ROOT_URL=https://${GITEA_DOMAIN}
      - GITEA__service__DISABLE_REGISTRATION=true
    restart: unless-stopped
    volumes:
      - ${GITEA_ROOT}:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - gitea_network
