version: "3"

networks:
  nextcloud_network:
  gitea_network:
    external: false
  registry_network:

services:
  swag:
    image: lscr.io/linuxserver/swag:2.6.0-ls232
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      - URL=${SWAG_URL}
      - SUBDOMAINS=${SWAG_SUBDOMAINS}
      - EXTRA_DOMAINS=${SWAG_EXTRA_DOMAINS}
      - VALIDATION=${SWAG_VALIDATION}
      - DNSPLUGIN=${SWAG_DNSPLUGIN}
      - EMAIL=${EMAIL}
      - CERTPROVIDER=${SWAG_CERTPROVIDER}
    volumes:
      - ${SWAG_ROOT}:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
    networks:
      - nextcloud_network
      - gitea_network
      - registry_network

  nextcloud:
    image: lscr.io/linuxserver/nextcloud:27.0.2-ls265
    container_name: nextcloud
    environment:
      - PUID=1000
      - GUID=1000
      - TZ=${TIMEZONE}
    volumes:
      - ${NEXTCLOUD_ROOT}/config:/config
      - ${NEXTCLOUD_ROOT}/data:/data
    depends_on:
      - mariadb
      - redis
    restart: unless-stopped
    networks:
      - nextcloud_network

  mariadb:
    image: lscr.io/linuxserver/mariadb:10.11.4-r0-ls110
    container_name: mariadb
    environment:
      - PUID=1000
      - GUID=1000
      - TZ=${TIMEZONE}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${NEXTCLOUD_ROOT}/mariadb:/config
    restart: unless-stopped
    networks:
      - nextcloud_network

  redis:
    image: redis:7.0.12-bookworm
    container_name: nextcloud-redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: unless-stopped
    networks:
      - nextcloud_network

  gitea:
    image: gitea/gitea:1.20.2
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - DOMAIN=${GITEA_DOMAIN}
      - RUN_MODE=prod
      - LFS_START_SERVER=true
      - GITEA__repository__DEFAULT_BRANCH=main
      - GITEA__oauth2__JWT_SECRET=${GITEA_JWT_SECRET}
      - GITEA__security__SECRET_KEY=${GITEA_SECRET_KEY}
      - GITEA__security__INTERNAL_TOKEN=${GITEA_INTERNAL_TOKEN}
      - GITEA__security__INSTALL_LOCK=true
      - GITEA__server__DISABLE_SSH=true
      - GITEA__server__LFS_JWT_SECRET=${GITEA_LFS_JWT_SECRET}
      - GITEA__server__ROOT_URL=https://${GITEA_DOMAIN}
      - GITEA__service__DISABLE_REGISTRATION=true
    restart: unless-stopped
    volumes:
      - ${GITEA_ROOT}:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - gitea_network

  # registry:
  #   image: registry:2.8.2
  #   container_name: registry
  #   volumes:
  #     - ${DOCKER_REGISTRY_ROOT}:/var/lib/registry
  #     - ${DOCKER_REGISTRY_ROOT}/auth:/auth
  #   environment:
  #     - REGISTRY_AUTH=htpasswd
  #     - REGISTRY_AUTH_HTPASSWD_REALM="Registry Realm"
  #     - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
  #   depends_on:
  #      - swag
  #   restart: always
  #   networks:
  #     - registry_network
