networks:
#  homebridge_network:
#    name: homebridge_network
  timemachine_network:
    name: timemachine_network

services:
  mqtt:
    image: eclipse-mosquitto:2.0.20
    container_name: mosquitto
    restart: unless-stopped
    volumes:
      - ${MOSQUITTO_ROOT}:/mosquitto
    command: "mosquitto -c /mosquitto-no-auth.conf"
    network_mode: host
#    ports:
#      - 1883:1883
#      - 9001:9001
#    networks:
#      - homebridge_network

  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:2.1.1
    container_name: zigbee2mqtt
    restart: unless-stopped
    environment:
      - TZ=${TIMEZONE}
    volumes:
      - ${ZIGBEE2MQTT_ROOT}:/app/data
      - /run/udev:/run/udev:ro
    devices:
      - ${ZIGBEE2MQTT_COORDINATOR_PORT}:/dev/ttyUSB0
    depends_on:
      - mqtt
    network_mode: host
#    ports:
#      - 8080:8080
#    networks:
#      - homebridge_network

  homebridge:
    image: homebridge/homebridge:2025-01-11
    container_name: homebridge
    restart: unless-stopped
    environment:
      - TZ=${TIMEZONE}
      - ENABLE_AVAHI=1
    volumes:
      - ${HOMEBRIDGE_ROOT}:/homebridge
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
    depends_on:
      - mqtt
      - zigbee2mqtt
    network_mode: host

  timemachine:
    image: mbentley/timemachine:smb
    container_name: timemachine
    restart: unless-stopped
    environment:
      - TZ=${TIMEZONE}
      - MIMIC_MODEL=TimeCapsule8,119
      - EXTERNAL_CONF=/users
      - PASSWORD=${TM_PASSWORD}
      - TM_UID=1000
      - TM_GID=1000
      - SET_PERMISSIONS=false
      - VOLUME_SIZE_LIMIT=0
    volumes:
      - ${TM_ROOT_WILLI}:/opt/willi
      - ${TM_ROOT_ANDREA}:/opt/andrea
      - ${TM_CONF_DIR}:/users
    tmpfs:
      - /run/samba
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    hostname: timemachine
#    network_mode: host
    ports:
      - 137:137/udp
      - 138:138/udp
      - 139:139
      - 445:445
    networks:
      - timemachine_network
